### ISSUE TITLE
Fjerne enkelstatutter fra innholdsfortegnelse

### ISSUE THREAD

**Issue by marthall** [abakus-ntnu/statutter#14]
Synes kanskje vi kan fjerne enkeltstatutter fra innholdsfortegnelsen. Underoverskrifter er dog fint å beholde.
![skjermbilde 2015-02-22 kl 17 13 02](https://cloud.githubusercontent.com/assets/3033550/6319264/29f4ad8c-bab6-11e4-84fb-b43318f3c80e.png)

**Comment by ekmartin** [comment]
+1
