### ISSUE TITLE
§8.3.4 i Abakus' statutter mangler linjeskift mellom avsnitt

### ISSUE THREAD

**Issue by marthall** [abakus-ntnu/statutter#19]
Ref. [§8.3.4](https://github.com/abakus-ntnu/statutter/blob/master/abakus-statutter/08-generalforsamling.tex#L73) i Abakus' statutter

**Comment by marthall** [comment]
Det er sikkert bare å legge på en ekstra linje i latex'en :)

**Comment by relekang** [comment]
Redigerte tittelen da det ikke er en generell ting, men §8.3.4 er lagt inn uten å bli delt opp i avsnitt, ved feiltagelse.

**Comment by marthall** [comment]
:+1:
