### ISSUE TITLE
Statutter burde inneholde paragraf-nummer

### ISSUE THREAD

**Issue by marthall** [abakus-ntnu/statutter#8]
Slik det er satt opp nå vil enkeltendringer kunne medføre at alle statutt-nummerene endres. Dette er litt uheldig, da enkle endringer kan få store følgefeil. Det vil være enklere å se hva som faktisk skjer om alle statuttene også har hardkodet paragraf-nummer. Statuttnummeret er også en del av statutten.

Hva tenker du @relekang ?

**Comment by relekang** [comment]
> Slik det er satt opp nå vil enkeltendringer kunne medføre at alle statutt-nummerene endres.

Har du et eksempel? Det eneste jeg ser som kan endre det nå er dersom man legger til en ny seksjon, subseksjon eller lignende før noen andre på samme nivå. Da er ikke det feil at nummerene endres fordi vi kan ikke ha 2 stk `§ 2.1`. Er det en case jeg ikke kommer på?

Det er mer arbeid å vedlikeholde og gir rom for redaksjonelle småfeil.

**Comment by marthall** [comment]
Lukker denne inntil videre. Vi ser hvordan det fungerer uten.

**Comment by relekang** [comment]
Jeg tror vi kan klare å få til dette på en bra måte :)
